name: "CI/CD: Frontend → Hosting • Backend → Cloud Run"

on:
  push:
    branches: [ main ]

env:
  FIREBASE_PROJECT_ID: prizepicksproject-15337

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install & build your React app
      - name: Build React app
        working-directory: frontEnd
        env:
          VITE_FIREBASE_API_KEY:     ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID:  ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID:      ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm ci
          npm run build

      # Deploy only the Hosting portion
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          channelId: live

      # 3) Authenticate to GCP _and_ configure gcloud + Docker
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4) Hook Docker into those creds
      - name: Configure Docker for GCR & Artifact Registry
        run: |
          # legacy Container Registry
          gcloud auth configure-docker gcr.io --quiet
          # (if you ever use Artifact Registry repos, include them too)
          # gcloud auth configure-docker us-west2-docker.pkg.dev --quie

      # Build & push your Flask Docker image
      - name: Build & Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/prizepicks-backend:$GITHUB_SHA backEnd
          docker push     gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/prizepicks-backend:$GITHUB_SHA

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy prizepicks-backend \
            --image gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/prizepicks-backend:$GITHUB_SHA \
            --region us-west2 \
            --platform managed \
            --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
            --quiet
